### ISSUE TITLE
Issue with Linux builds

### ISSUE THREAD

**Issue by WolfgangSenff** [dulvui/godot-4-html-export#1]
Hi. Through a random series of events, I was attempting to use this action for my own purposes and found that my project will not export on Linux. There's a known issue right now (several of them) where Linux and Mac do not properly export - here's just one example: https://github.com/godotengine/godot/issues/77007

Would it be possible to get an update for this so it supports Windows builds? I noticed the caching mechanism, at least, seems to break when not using Linux, which is weird, but true for me.

**Comment by dulvui** [comment]
Hello! I could surely add the Windows runner support, but all steps would be different, since Windows has a different executable that needs to be downloaded and extracted to the correct folders etc. So in my view it would make even more sense to create a complete new action for windows. Or also a simple if `${{ runner.os }} == Windows` and `${{ runner.os }} == Linux` would do the job, so it would work for both OS in the same action here.
The only problem is, that I don't have any Windows machine, so I don't know Godot's configuration folder structure on Windows. If you can provide me the needed details for Windows I could try directly with the Github's Windows runners.
I actually think the export templates location on Windows should be enough.

**Comment by WolfgangSenff** [comment]
This is generally where the export templates end up going:
C:/Users/USER_NAME/AppData/Roaming/Godot/export_templates/4.2.stable

Obviously, USER_NAME is specific to the machine. Is that helpful?

**Comment by dulvui** [comment]
Yes this helps, thank you!

**Comment by dulvui** [comment]
I actually didn't have to create a new repository, some dynamic env variables where enough. It is not complete yet, since I have to fix some windows/unix  paths issues, but currently it works with version 0.0.2.
It doesn't work correctly yet, but I'll fix the last issues tomorrow.

Here you can see that the Godot initialization worked, only the export has then errors, but that might be because of problems with my game.
https://github.com/dulvui/futsal-manager/actions/runs/7120625055/job/19389372245

**Comment by WolfgangSenff** [comment]
Those are the exact errors that I got as well, but they prevent it from running on my machine - so it's possible that this isn't limited to Linux/Mac. That is annoying.

**Comment by dulvui** [comment]
I removed Windows runners support, since it's quite complicated to maintain everything for different operating systems. Config files, export templates, download links etc.. have different values for each OS, so making one dedicated action for every OS makes more sense to me.
Now only Linux runners are supported.

In case if needed I could setup a separate action dedicated for windows.
